### ISSUE TITLE
训练效果没有达到预期

### ISSUE THREAD

**Issue by xyzyx233** [starry-sky6688/DyMA-CL#1]
我在自己环境下，按照Readme里的说明从头开始训练。首先在8m的环境下进行训练，全部参数为默认。训练完成后，将得到模型重命名为3m再次训练。这样的得到的结果，并没有达到预期。
8m的条件下，训练输出的结果
![plt_7](https://user-images.githubusercontent.com/18461533/103328086-5ebc2000-4a92-11eb-8fd9-4aadaf6fbbdd.png)
迁移后的训练结果
![plt_7](https://user-images.githubusercontent.com/18461533/103328105-71cef000-4a92-11eb-8975-2b8770c41903.png)

**Comment by starry-sky6688** [comment]
应该是模型命名或者路径有问题，要把模型放到'3m'对应的文件夹中，模型名字要把后面的下划线+数字去掉。

要加载的模型的完整路径应该是 './model/dyma/3m/rnn_net_params.pkl'、'./model/dyma/3m/vdn_net_params.pkl'

你可以看一下console里面有没有输出 'Successfully load the model:   .......'这句话，如果输出则表示模型加载上了。
