### ISSUE TITLE
Training mode and some details

### ISSUE THREAD

**Issue by Sobbbbbber** [starry-sky6688/DyMA-CL#3]
Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:

If I want to train from scratch, I need to train twice, is it right?
1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary. 
2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.

**Comment by Sobbbbbber** [comment]
Besides, do u realize the buffer reuse in the code?

**Comment by starry-sky6688** [comment]
> Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> 
> If I want to train from scratch, I need to train twice, is it right?
> 
> 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.

Absolutely right

**Comment by Sobbbbbber** [comment]
> > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > If I want to train from scratch, I need to train twice, is it right?
> > 
> > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> 
> Absolutely right



> > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > If I want to train from scratch, I need to train twice, is it right?
> > 
> > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> 
> Absolutely right

how to realize the buffer reuse between in these two training processes? I think they are two independent training processes.

**Comment by starry-sky6688** [comment]
> Besides, do u realize the buffer reuse in the code?

The buffer was reused and u can see it in https://github.com/starry-sky6688/DyMA-CL/blob/a36c992d34f8fa0821cefdf61f04ba5f89d2ed77/runner.py#L57

**Comment by starry-sky6688** [comment]
> > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > If I want to train from scratch, I need to train twice, is it right?
> > > 
> > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > 
> > 
> > Absolutely right
> 
> > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > If I want to train from scratch, I need to train twice, is it right?
> > > 
> > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > 
> > 
> > Absolutely right
> 
> how to realize the buffer reuse between in these two training processes? I think they are two independent training processes.

The buffers of the two training processes are independent and not reused

**Comment by Sobbbbbber** [comment]
> > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > If I want to train from scratch, I need to train twice, is it right?
> > > > 
> > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > 
> > > 
> > > Absolutely right
> > 
> > 
> > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > If I want to train from scratch, I need to train twice, is it right?
> > > > 
> > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > 
> > > 
> > > Absolutely right
> > 
> > 
> > how to realize the buffer reuse between in these two training processes? I think they are two independent training processes.
> 
> The buffers of the two training processes are independent and not reused

Thanks for your reply. Besides, the buffer reuse and curriculum distillation proposed in original paper are not implement. Right?

**Comment by starry-sky6688** [comment]
> > > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > > If I want to train from scratch, I need to train twice, is it right?
> > > > > 
> > > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > > 
> > > > 
> > > > Absolutely right
> > > 
> > > 
> > > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > > If I want to train from scratch, I need to train twice, is it right?
> > > > > 
> > > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > > 
> > > > 
> > > > Absolutely right
> > > 
> > > 
> > > how to realize the buffer reuse between in these two training processes? I think they are two independent training processes.
> > 
> > 
> > The buffers of the two training processes are independent and not reused
> 
> Thanks for your reply. Besides, the buffer reuse and curriculum distillation proposed in original paper are not implement. Right?

Right

**Comment by Sobbbbbber** [comment]
> > > > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > > > If I want to train from scratch, I need to train twice, is it right?
> > > > > > 
> > > > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > > > 
> > > > > 
> > > > > Absolutely right
> > > > 
> > > > 
> > > > > > Hi, thanks for your implementations, which are clear and helpful. However, I have some questions about the details and ask you for help:
> > > > > > If I want to train from scratch, I need to train twice, is it right?
> > > > > > 
> > > > > > 1. I need to train on the 8m task completely (until the model converges), then save the model into the dictionary.
> > > > > > 2. After that, I need to train on the 3m task, and load the pretrained model at the initialization stage. Then I need to train it until the end.
> > > > > 
> > > > > 
> > > > > Absolutely right
> > > > 
> > > > 
> > > > how to realize the buffer reuse between in these two training processes? I think they are two independent training processes.
> > > 
> > > 
> > > The buffers of the two training processes are independent and not reused
> > 
> > 
> > Thanks for your reply. Besides, the buffer reuse and curriculum distillation proposed in original paper are not implement. Right?
> 
> Right

OK, thanks for your help again~
